//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Menu
    {
        public int id { get; set; }
        public string name { get; set; }
        public string groupName { get; set; }
        public Nullable<double> orderValue { get; set; }
        public string url { get; set; }
        public string contentText { get; set; }
        public Nullable<System.DateTime> createdOn { get; set; }
        public Nullable<System.DateTime> updatedOn { get; set; }
        public Nullable<bool> active { get; set; }
        public Nullable<bool> deleted { get; set; }
    }
}
